#!/bin/bash

# Configuration for borders: https://github.com/FelixKratz/JankyBorders
options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xff89b4fa   # Catppuccin blue (active)
	inactive_color=0x00000000 # Invisible (inactive)
)

borders "${options[@]}"
