tap "homebrew/bundle"
tap "gitguardian/tap"
tap "FelixKratz/formulae"   # for sketchybar
tap "sst/tap"               # for opencode

# ───────────────────────────────
# CLI Utilities
# ───────────────────────────────
brew "bat"                  # better cat
brew "btop"                 # system monitor
brew "eza"                  # better ls
brew "fx"                   # json viewer
brew "fzf"                  # fuzzy finder
brew "grep"                 # text search
brew "rg"                   # file search (used by nvim)
brew "thefuck"              # fix typos
brew "tldr"                 # short man pages
brew "zoxide"               # fast cd
brew "zsh-autosuggestions"  # zsh helper
brew "zsh-syntax-highlighting" # zsh colors
brew "zsh-completions"      # zsh completions
brew "zsh-autocomplete"     # zsh autocomplete
brew "jq"                   # required by xcodebuild.nvim
brew "nmap"                 # network scanner

brew "neovim"               # editor
brew "tmux"                 # terminal multiplexer

brew "opencode"             # ai code cli
brew "lazygit"              # git ui
brew "starship"             # shell prompt
brew "delta"                # git diff tool

brew "pass"                 # password manager
brew "gpg"                  # encryption tool for pass
brew "openssh"              # ssh tool

# ───────────────────────────────
# Dev & Build Tools
# ───────────────────────────────
brew "ansible"              # automation
brew "delve"                # go debugger (nvim DAP)
brew "git"                  # version control
brew "go"                   # go lang
brew "python"               # scripting
brew "xcodegen"             # xcode project gen
brew "ruby"                 # ruby lang

# all those below are required by xcodebuild.nvim. Some might have been listed above already.
brew "xcode-build-server"   
brew "xcbeautify"
brew "ruby"
brew "pipx"
brew "rg"
brew "jq"
brew "coreutils"

# Database Tools
# make sure to run "brew link --force libpq" afterwards
brew "libpq"                # postgres tools

# ───────────────────────────────
# Networking & Package Management
# ───────────────────────────────
brew "curl"
brew "wget"


# ───────────────────────────────
# Formatter & Linter Tools
# some formatter and linter used in neovim plugins
# ───────────────────────────────
brew "prettier"             # JS/TS formatter
brew "swiftformat"
brew "swiftlint"
brew "xcbeautify"

# ───────────────────────────────
# Desktop UI & Automation
# sketchybars and borders are started with aerospace.
# Otherwise manually run:
#   brew services start sketchybar
#   brew services start borders
# ───────────────────────────────
brew "borders"
brew "sketchybar"

# ───────────────────────────────
# Applications (Casks)
# ───────────────────────────────
cask "iterm2"
cask "wezterm"
cask "ghostty"
cask "docker-desktop"
cask "mitmproxy"
cask "sourcetree"
cask "tailscale-app"

cask "postman"
cask "sublime-text"
cask "xcodes-app"
cask "swiftformat-for-xcode"

cask "raycast"
cask "notion"
cask "google-chrome"
cask "shortcat"
cask "alt-tab"
cask "sf-symbols"
cask "nikitabobko/tap/aerospace"
### currently installed manually. Uncomment once v. 0.11.13 is released
# cask "jordanbaird-ice"
