# Font
font_family JetBrainsMono Nerd Font
font_size 13.0
text_composition_strategy legacy

# Appearance
include themes/catppuccin-mocha.conf
background #181825
window_padding_width 0
hide_window_decorations titlebar-only

# Tabs
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
tab_title_max_length 18
active_tab_foreground #181825
active_tab_background #7aa2f7
inactive_tab_foreground #7aa2f7
inactive_tab_background #181825
tab_bar_background #181825

# Behavior
scrollback_lines 10000
enable_audio_bell no
